
language: java
env:
  - COVERALLS_TOKEN=OG8RAhndMR8qNlH8e1YUuN85ikl18mYU3
sudo: false
branches:
  only:
  - develop
jdk:
  - oraclejdk8
script:
  - |
    cd tf-maven-plugin
    ./mvnw clean test jacoco:report coveralls:report
