# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    branches:
      only:
        - develop
        - /^release\/v.*$/
        - /^hotfix\/v.*$/

    steps:
      - checkout



      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd tf-build-tools && ./mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run maven build!
      - run:
          shell: /bin/sh
          command: |
             pwd
             cd tf-build-tools
             echo "*** Downloading the help plugin and getting the project version ***"
             ./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version
             VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

             if [ $CIRCLE_PULL_REQUEST = "" ] && echo $VERSION | grep -q SNAPSHOT; then
               echo "*** Validating the build and deploying to Sonatype SNAPSHOT repo ***"
               cp ../.mvn.settings.xml ~/.m2/settings.xml && ./mvnw clean test coveralls:report deploy
             else
               echo "*** Validating the build ***"
               ./mvnw clean test coveralls:report
             fi
