#!/usr/bin/env bash
args="$@"
cur_loc='pwd'
target_cd="$cur_loc/.tf"
projectBaseDir=""

while [[ $projectBaseDir == "" ]]
do
    if [ -d "$target_cd" ]
    then
        projectBaseDir="$cur_loc"
    else
        cd ..
        cur_loc=`pwd`
        target_cd="$cur_loc/.tf"
    fi
done
targetDir="$projectBaseDir/.tf/"
propFile="${targetDir}terraform-maven.properties"
search="="

while IFS= read -r line
do
  case $line in
  *"distributionSite"*)
    distributionSite=${line#*$search}
    ;;
  *"releaseDir"*)
    releaseDir=${line#*$search}
    ;;
  *"releaseName"*)
    releaseName=${line#*$search}
    ;;
  *"releaseVer"*)
    releaseVer=${line#*$search}
    ;;
  *"releaseOS"*)
    releaseOS=${line#*$search}
    ;;
  *"releaseSuffix"*)
    releaseSuffix=${line#*$search}
    ;;
  esac
done < "$propFile"

terraformZip="${targetDir}${releaseName}_${releaseVer}_${releaseOS}_${releaseSuffix}"
terraformBinary="${targetDir}terraform.exe"
releaseSource="${distributionSite}/${releaseDir}/${releaseVer}/${releaseName}_${releaseVer}_${releaseOS}_${releaseSuffix}"

if [ -f $terraformBinary ]
then
    versionString=`$terraformBinary -version`
    search="Terraform v"
    rest=${versionString#*$search}
    installedVerion=`echo $rest|cut -d ' ' -f 1`

    if [[ $installedVerion == $releaseVer ]]
    then
        echo ""
    else
        echo "Different version, downloading"
        curl -o $terraformZip $releaseSource
        rm $terraformBinary
        unzip -d $targetDir $terraformZip
        rm $terraformZip
    fi
else
    echo "Terraform not found, installing"
    curl -o $terraformZip $releaseSource
    if [ -f $terraformBinary ]
    then
        rm $terraformBinary
    fi
    unzip -d $targetDir $terraformZip
    rm $terraformZip
fi

maven_java_exe="${JAVA_HOME}/bin/java.exe"

$terraformBinary "$args"
exit
